# Generated by Django 5.2 on 2025-04-20 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userprofile_department_en_userprofile_department_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='department_en',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='department_ru',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='department_uz',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='position_en',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='position_ru',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='position_uz',
        ),
    ]
