# Generated by Django 5.2 on 2025-04-19 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachment', '0001_initial'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='filename_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attachment',
            name='filename_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attachment',
            name='filename_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attachment',
            name='task_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='task.task'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='task_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='task.task'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='task_uz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='task.task'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='task.task'),
        ),
    ]
